### ISSUE TITLE
Where is the /dist directory?

### ISSUE THREAD

**Issue by lidiawarnes** [vmware/weathervane#91]
autoSetup.pl expects a /dist directory under /root/weathervane and a number of files such as auctionWeb.war, auction.war etc in this directory. The directory is not on the github. What am I missing?

**Comment by hrosenbe** [comment]
It looks like a section got deleted from the User's Guide that discusses building the executables, which is why you can't find any reference to that step.  I will fix the guide, but in the meantime here are the instructions:

To build the executables, cd into the /root/weathervane directory, and then issue the command:

_./gradlew clean release_

This will create the dist directory and populate it with all of the required files.

Building the executables is supposed to happen before running the autoSetup.pl script.  This is because one of the things done by that script is to copy the executables into the proper locations on the VM.  You can re-run the autoSetup.pl script after building the executables.  You will get errors, which you can ignore, and the files will get copied to the proper locations.

Sorry about the confusion.  Let us know if you have any additional questions.

**Comment by lidiawarnes** [comment]
Thank you for the quick reply. The gradlew script results in the following error as it tries to download the latest clean version of gradle

Downloading https://services.gradle.org/distributions/gradle-2.11-bin.zip

Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnectio
n.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:17
7)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by hrosenbe** [comment]
That is odd.  I tried building from a fresh VM thinking that perhaps that older version of gradle had been removed (we are upgrading to Gradle 5.4.1 in the upcoming release), but it worked just fine.

Do you need to use an http proxy on the network where you were building weathervane? Can you get to the url _https://services.gradle.org/distributions/_ in a browser, or by running _curl https://services.gradle.org/distributions/_ at the command-line?

**Comment by lidiawarnes** [comment]
I have thought about the proxy settings as well and I have updated the environment to the correct settings. I am still getting the error running the gradlew script. I am able to open the distributions webpage below on the machine where I intend to setup weathervane. I can download a version of gradle and create an unzipped gradle directory under /root/weathervane but I am not sure the script will work and I am trying to avoid manually going through all the steps the script is automating.

Lidia Warnes
Intel Corporation
lidia.warnes@intel.com<mailto:lidia.warnes@intel.com>
phone: 916-356-4340

**Comment by lidiawarnes** [comment]
I have thought about the proxy settings as well and I have updated the environment to the correct settings. I am still getting the error running the gradlew script. I am able to open the distributions webpage below on the machine where I intend to setup weathervane. I can download a version of gradle and create an unzipped gradle directory under /root/weathervane but I am not sure the script will work and I am trying to avoid manually going through all the steps the script is automating.

**Comment by hrosenbe** [comment]
I have to admit that I am stumped by this.  You could try building on a different system and then copying the dist directory to your Weathervane host.  I often build on my Mac.  I don't know whether it will work on a Windows system (I don't have access to one), but whichever system you use you will need to have the Java JDK installed (at least Java 8).

**Comment by lidiawarnes** [comment]
I am using Linux, CentoOS7.4. I will check the Java version and try again.

**Comment by lidiawarnes** [comment]
I have worked around some of the issues associated with running the benchmark behind a corporate firewall - learned a lot more about proxy settings. And I was able to resolve the this problem. I am currently running into issue 47/49 ...

Thank you for your help.

**Comment by bhoflich** [comment]
Closing version 1.x issue, which is no longer being maintained.
